language: node_js
git:
  depth: 1
  quiet: true
branches:
  only:
    - trunk
    - /^test\/.*$/
  except:
    - /^hack\/.*$/
script: npx jest
jobs:
  include:
    - node_js: 18
      env: TEST_TARGET=node
    - node_js: 16
      env: TEST_TARGET=node
