language: node_js
git:
  depth: 1
  quiet: true
branches:
  only:
    -  trunk
    - /^test\/.*$/
  except:
    - /^hack\/.*$/
script: npx jest
jobs:
  include:
    - node_js: 10
    - node_js: 12
    - node_js: 14
